### ISSUE TITLE
Add + / - buttons to dice roller

### ISSUE THREAD

**Issue by mgamlem3** [mg3-codes/d-d-spell-finder#117]
Mobile only?

**Comment by mohibkay** [comment]
Hey, @mgamlem3, could you please help me with understanding this issue?
I would like to work on this.

**Comment by mgamlem3** [comment]
Sorry @mohibkay. Somehow I missed this comment. I opened #126 which could maybe be a good one for you to take a look at if you are interested in another issue. Let me know if you have any questions or if you want me to assign it to you.
