### ISSUE TITLE
GitHub button can be blue instead of black

### ISSUE THREAD

**Issue by mgamlem3** [mg3-codes/d-d-spell-finder#118]
## Context:
I observed this on iPad while on the /dice-roller page.

## Expected behavior
- GitHub icon/link should always be black in light mode and always be white in dark mode.
- Color should be Bootstrap SCSS white or black.

**Comment by mohibkay** [comment]
Hey @mgamlem3, could you please assign this issue to me?

I ran the repo locally and changed the Github button color to blue using the Bootstrap CSS class `text-primary`.
Thanks
<img width="1512" alt="Screenshot 2023-06-09 at 2 27 40 PM" src="https://github.com/mg3-codes/d-d-spell-finder/assets/66241121/cba30651-69da-450c-8ece-f8b73f72c1ee">
<img width="1512" alt="Screenshot 2023-06-09 at 2 26 52 PM" src="https://github.com/mg3-codes/d-d-spell-finder/assets/66241121/8e41a860-adfa-412f-9169-c66ce7807c58">

**Comment by mohibkay** [comment]
P.S.: This is my first OSS contribution. Please let me know if I make any mistakes. 
I will be grateful to you.
